### ISSUE TITLE
Control Tapo with wget / curl?

### ISSUE THREAD

**Issue by rodajc** [almottier/TapoP100#10]
This is a question rather than an issue.

The question is: Is it possible to control Tapo devices with wget / curl?

I'm asking because I want to control them from an openwrt router and I suspect it's difficult to get python up and running there. More difficult than wget / curl anyway.

Is it because of encryption?

**Comment by almottier** [comment]
It would be VERY challenging to handle crypto, openssl etc... using plain bash. 
I use a raspberry pi zero w and it works great.

**Comment by rodajc** [comment]
The solution was a different smart plug and TuyaConvert to flash it with Tasmota:
[GHome Smart Plug](https://github.com/arendst/Tasmota/discussions/20182#discussioncomment-7807334)
