### ISSUE TITLE
Tapo P115

### ISSUE THREAD

**Issue by rodajc** [almottier/TapoP100#12]
Does TapoP100 support the Tapo P115 smart plug?

**Comment by martijnende** [comment]
I just tried it out today, and I can confirm that the library is compatible with the P115. Use `PyP100.PyP100` to get device info and to control the plug (on/off), use `PyP100.PyP110` to get the power state.

**Comment by rodajc** [comment]
Thanks. I finally adopted a completely different approach using [GHome devices with Tasmota](https://github.com/arendst/Tasmota/discussions/20182). Highly recommended.
